name: Push

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  ## Run main CI build and tests.
  run-ci:
    name: "Build & Test"
    uses: ./.github/workflows/ci.yml
    permissions:
      actions: write
      contents: write

  ## Publish and check the dependency graph.
  checks-dependency-graph:
    name: "Checks"
    uses: ./.github/workflows/dependency-review.yml
    permissions:
      contents: write
      id-token: write

  ## Validate the Gradle Wrapper binary
  checks-gradle-wrapper:
    name: "Checks"
    uses: ./.github/workflows/gradle-wrapper-validation.yml
