name: Push

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  ## Run main CI build and tests.
  run-ci:
    name: "Build & Test"
    uses: ./.github/workflows/ci.yml

  ## Publish and check the dependency graph.
  checks-dependency-graph:
    name: "Checks"
    uses: ./.github/workflows/dependency-review.yml

  ## Run CodeQL checks
  checks-codeql:
    name: "Checks"
    uses: ./.github/workflows/codeql.yml
